version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo-franchise
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - franchise-network

volumes:
  mongo-data:

networks:
  franchise-network:
