spring:
  application:
    name: franchise-api

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/franchise-db}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8080}