spring:
  application:
    name: franchise-api

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://franchise_user:Vz8cpEYLAP2dX6L5@cluster0.larqj8l.mongodb.net/franchise-db?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always